addons:
  apt:
    packages:
    - doxygen
    - graphviz
    - libssl-dev
    - autoconf
    - automake
    - libtool

language: c

script: ./autogen.sh && ./configure --prefix=/usr --with-pic && make

install: true

sudo: false

notifications:
  irc: "chat.freenode.net#code-hell"

